apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo
spec:
  nodeSelector:
    workload: mongodb
  containers:
    - name: mongo
      image: mongo:latest
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: MONGO_ROOT_USER
        - name: MONGO_ROOT_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: MONGO_ROOT_PASS
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumes:
    - name: mongo-data
      persistentVolumeClaim:
        claimName: mongo-pvc