apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo-replicaset
  namespace: mongo-ns
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        workload: mongodb
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: MONGO_ROOT_USER
            - name: MONGO_ROOT_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: MONGO_ROOT_PASS
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc